In [1]:
with open("the-verdict.txt","r",encoding="utf-8") as f:
  raw_text = f.read()

print("Total Charectors / letters including space : ",len(raw_text))

print(raw_text[:20])

Total Charectors / letters including space :  20479
I HAD always thought


In [2]:
import re

pre_processed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
pre_processed = [x.strip() for x in pre_processed if x.strip()]
print(pre_processed[:20])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was']


In [3]:
print(len(pre_processed))

4690


In [4]:
all_words = sorted(set(pre_processed))
print(all_words[:50])
vocabulary_size = len(all_words)
print(vocabulary_size)

['!', '"', "'", '(', ')', ',', '--', '.', ':', ';', '?', 'A', 'Ah', 'Among', 'And', 'Are', 'Arrt', 'As', 'At', 'Be', 'Begin', 'Burlington', 'But', 'By', 'Carlo', 'Chicago', 'Claude', 'Come', 'Croft', 'Destroyed', 'Devonshire', 'Don', 'Dubarry', 'Emperors', 'Florence', 'For', 'Gallery', 'Gideon', 'Gisburn', 'Gisburns', 'Grafton', 'Greek', 'Grindle', 'Grindles', 'HAD', 'Had', 'Hang', 'Has', 'He', 'Her']
1130


In [5]:
vocab = {token:i for i,token in enumerate(all_words)}
print(vocab)

{'!': 0, '"': 1, "'": 2, '(': 3, ')': 4, ',': 5, '--': 6, '.': 7, ':': 8, ';': 9, '?': 10, 'A': 11, 'Ah': 12, 'Among': 13, 'And': 14, 'Are': 15, 'Arrt': 16, 'As': 17, 'At': 18, 'Be': 19, 'Begin': 20, 'Burlington': 21, 'But': 22, 'By': 23, 'Carlo': 24, 'Chicago': 25, 'Claude': 26, 'Come': 27, 'Croft': 28, 'Destroyed': 29, 'Devonshire': 30, 'Don': 31, 'Dubarry': 32, 'Emperors': 33, 'Florence': 34, 'For': 35, 'Gallery': 36, 'Gideon': 37, 'Gisburn': 38, 'Gisburns': 39, 'Grafton': 40, 'Greek': 41, 'Grindle': 42, 'Grindles': 43, 'HAD': 44, 'Had': 45, 'Hang': 46, 'Has': 47, 'He': 48, 'Her': 49, 'Hermia': 50, 'His': 51, 'How': 52, 'I': 53, 'If': 54, 'In': 55, 'It': 56, 'Jack': 57, 'Jove': 58, 'Just': 59, 'Lord': 60, 'Made': 61, 'Miss': 62, 'Money': 63, 'Monte': 64, 'Moon-dancers': 65, 'Mr': 66, 'Mrs': 67, 'My': 68, 'Never': 69, 'No': 70, 'Now': 71, 'Nutley': 72, 'Of': 73, 'Oh': 74, 'On': 75, 'Once': 76, 'Only': 77, 'Or': 78, 'Perhaps': 79, 'Poor': 80, 'Professional': 81, 'Renaissance': 82, 'Ri

In [6]:
class simpletokenizerV1: # cant handle data is the words are missing in vocabulary
  def __init__(self,vocab):
    self.str_to_id = vocab
    self.id_to_str = {i:s for s,i in vocab.items()}

  def encode(self,text):
    pre_processed = re.split(r'([,.:;?_!"()\']|--|\s)',text)
    pre_processed = [x.strip() for x in pre_processed if x.strip()]

    ids = [self.str_to_id[words] for words in pre_processed]
    return ids

  def decode(self,ids):
    text = " ".join([self.id_to_str[i] for i in ids])
    text = re.sub(r'\s+([,.?!"()\'])',r'\1',text)
    return text

In [7]:
st= simpletokenizerV1(vocab)
text_encoded=st.encode(raw_text)
print(len(text_encoded))

4690


In [8]:
all_tokens = sorted(list(set(pre_processed)))
all_tokens.extend(["<|endoftext|>","<|unk|>"])

print(all_tokens[-2])

vocab = {token:i for i,token in enumerate(all_tokens)}
print(len(vocab))

<|endoftext|>
1132


In [9]:
list(vocab.items())[-5:]

[('younger', 1127),
 ('your', 1128),
 ('yourself', 1129),
 ('<|endoftext|>', 1130),
 ('<|unk|>', 1131)]

In [10]:
class simpletokenizerV2:
  def __init__(self,vocab):
    self.str_to_id = vocab
    self.id_to_str = { token:word for word,token in vocab.items()}

  def encode(self,text):
    pre_processed = re.split(r'([,.:;?_!"()\']|--|\s)',text)
    pre_processed = [x.strip() for x in pre_processed if x.strip()]
    pre_processed = [ word if word in self.str_to_id else "<|unk|>" for word in pre_processed]

    ids = [self.str_to_id[word] for word in pre_processed]
    return ids

  def decode(self,ids):
    text = " ".join([self.id_to_str[id] for id in ids])
    text = re.sub(r'\s+([,.?!"()\'])',r'\1',text)
    return text


In [11]:
tokenizer = simpletokenizerV2(vocab)

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1, text2)) #Make sure that there is space on boldside of <|endoftext|>

print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


In [12]:
list(vocab.items())[-2:]

[('<|endoftext|>', 1130), ('<|unk|>', 1131)]

In [13]:
tokenizer.encode(text)

[1131, 5, 355, 1126, 628, 975, 10, 1130, 55, 988, 956, 984, 722, 988, 1131, 7]

In [14]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.'

In [15]:
!pip3 install tiktoken

In [16]:
import tiktoken
tokenizer = tiktoken.get_encoding("gpt2")

In [17]:
text = (
    "Hello, whatsup <|endoftext|> how to doing."
)

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

[15496, 11, 644, 37330, 220, 50256, 703, 284, 1804, 13]


In [18]:
tokenizer.decode(integers)

'Hello, whatsup <|endoftext|> how to doing.'

In [19]:
with open("the-verdict.txt","r",encoding="utf-8") as f:
  raw_text = f.read()
encoded_txt= tokenizer.encode(raw_text)
len(encoded_txt)

5145

In [20]:
enc_txt = encoded_txt[50:]


In [21]:
from torch.utils.data import Dataset,DataLoader
import torch

class GPTDatasetV1(Dataset):
  def __init__(self,txt,tokenizer,max_length,stride):
    self.input_ids=[]
    self.target_ids=[]

    token_ids =tokenizer.encode(txt,allowed_special={"<|endoftext|>"})

    for i in range(0,len(token_ids)-max_length,stride):
      input_seq =  token_ids[i:i+max_length]
      target_seq = token_ids[i+1:i+1+max_length]
      self.input_ids.append(torch.tensor(input_seq))
      self.target_ids.append(torch.tensor(target_seq))

  def __len__(self):
    return len(self.input_ids)

  def __getitem__(self,idx):
    return self.input_ids[idx],self.target_ids[idx]

/home/thoth/Desktop/LLM/venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [22]:
def create_dataloader_v1(txt, batch_size=4, max_length=256,
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    tokenizer = tiktoken.get_encoding("gpt2")

    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [23]:
with open("the-verdict.txt","r",encoding="utf-8") as f:
  raw_text = f.read()

dl= create_dataloader_v1(raw_text,batch_size=1,max_length=4,stride=1,shuffle=False)

data_iter = iter(dl)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [24]:
# 4 is the vocabulary size, and 5 is the embedding dimension (number of features per word)
embedding = torch.nn.Embedding(4, 5)

idx = torch.tensor([2, 1, 0, 3])  # Valid indices for a vocabulary of size 4

embedded_vectors = embedding(torch.tensor([2]))
print("Embedded vectors:\n", embedded_vectors)
print("Embedding weights:\n", embedding.weight)

Embedded vectors:
 tensor([[ 0.7909,  0.4557, -0.2146, -0.9399,  1.7612]],
       grad_fn=<EmbeddingBackward0>)
Embedding weights:
 Parameter containing:
tensor([[ 1.0081,  1.2799,  0.2303,  0.7247,  1.7831],
        [ 1.6580, -0.6892,  0.5038, -1.6243, -0.2777],
        [ 0.7909,  0.4557, -0.2146, -0.9399,  1.7612],
        [-1.2454,  0.8675,  0.5492,  1.0677, -0.0800]], requires_grad=True)


In [25]:
vocab_size = 50257
output_dim = 256

token_embedings = torch.nn.Embedding(vocab_size,output_dim)

In [26]:
dl= create_dataloader_v1(raw_text,batch_size=8,max_length=4,stride=4,shuffle=False)

data_iter = iter(dl)
first_batch = next(data_iter)
print(first_batch)

[tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]]), tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])]


In [27]:
vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

token_embedings = token_embedding_layer(inputs)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape:
 torch.Size([8, 4])


In [28]:
token_embedings.shape 
''' 1 first we made a vocabu;ary and tokenized it 
    2 . then we made input output batches and tokenized it 
    3. we converted token vocab to vector embeddings.
    4. Converted input output batches to vector embeddings each token has 256 features and in each input there are 4 sets of 8 tokens'''

' 1 first we made a vocabu;ary and tokenized it \n    2 . then we made input output batches and tokenized it \n    3. we converted token vocab to vector embeddings.\n    4. Converted input output batches to vector embeddings each token has 256 features and in each input there are 4 sets of 8 tokens'

In [29]:
# Positional encodings - so the size is number of tokens to predict the same number of output in this case its four so 4 rows and same 256 features for this e4 tokens 4 beacuse postion of only 4
position_embedding_layer  = torch.nn.Embedding(max_length,256)
position_embedding = position_embedding_layer(torch.arange(max_length)) # accessing those in the form of list with their index number
position_embedding.shape

torch.Size([4, 256])

In [30]:
import torch
# We want context vector for journey 
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

context_vector_for = inputs[1] # journey
row_for_weights = inputs.shape[1]
columns_for_weights = 2 # So its just like passing inputs to  two neurons and gives output from these neurons for all rows 

In [31]:
context_vector_for,row_for_weights

(tensor([0.5500, 0.8700, 0.6600]), 3)

In [32]:
# Weights intilization for those 2 neurons 
# We aew also using 3 such ANN so there are 3 such weights and 3 output vectors 
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(row_for_weights,columns_for_weights),requires_grad=False)
W_key  = torch.nn.Parameter(torch.rand(row_for_weights,columns_for_weights),requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(row_for_weights,columns_for_weights),requires_grad=False)

In [33]:
query_vect_for_journey  = context_vector_for @ W_query
key_vect_for_journey  = context_vector_for @ W_key
value_vect_for_journey  = context_vector_for @ W_value

In [34]:
print(query_vect_for_journey,W_query)

tensor([0.4306, 1.4551]) Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])


In [35]:
# For all inputs 
query_vect  = inputs @ W_query
key_vect  = inputs @ W_key
value_vect  = inputs @ W_value
query_vect.shape,key_vect.shape,value_vect.shape

(torch.Size([6, 2]), torch.Size([6, 2]), torch.Size([6, 2]))

In [36]:
# Attention score is dot product between query and key so for a journey query we will take dot product with all the key values 
# same can be done for all the other queries 

attention_score = query_vect @ key_vect.T
attention_score.shape # so we will have score for all the tokens with respect to other tokens

torch.Size([6, 6])

In [37]:
attention_score

tensor([[0.9231, 1.3545, 1.3241, 0.7910, 0.4032, 1.1330],
        [1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440],
        [1.2544, 1.8284, 1.7877, 1.0654, 0.5508, 1.5238],
        [0.6973, 1.0167, 0.9941, 0.5925, 0.3061, 0.8475],
        [0.6114, 0.8819, 0.8626, 0.5121, 0.2707, 0.7307],
        [0.8995, 1.3165, 1.2871, 0.7682, 0.3937, 1.0996]])

In [38]:
# Normalize attention score 
dim = key_vect.shape[-1]
attention_weights = torch.softmax(attention_score/ dim**0.5 ,dim=-1) # Scaled dot product attention
#  squre root reduces or keeps the variance close to one even if dimension increases for key and query also helps in softmax 
attention_weights

tensor([[0.1551, 0.2104, 0.2059, 0.1413, 0.1074, 0.1799],
        [0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820],
        [0.1503, 0.2256, 0.2192, 0.1315, 0.0914, 0.1819],
        [0.1591, 0.1994, 0.1962, 0.1477, 0.1206, 0.1769],
        [0.1610, 0.1949, 0.1923, 0.1501, 0.1265, 0.1752],
        [0.1557, 0.2092, 0.2048, 0.1419, 0.1089, 0.1794]])

In [39]:
sum(attention_weights[0])        

tensor(1.)

In [40]:
context_vector = attention_weights @ value_vect
context_vector.shape

torch.Size([6, 2])

In [41]:
context_vector

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]])

In [42]:
class Self_Attention_V1(torch.nn.Module):
    def __init__(self,d_in,d_out):
        super().__init__()
        self.W_query = torch.nn.Parameter(torch.rand(d_in,d_out))
        self.W_key  = torch.nn.Parameter(torch.rand(d_in,d_out))
        self.W_value = torch.nn.Parameter(torch.rand(d_in,d_out))

    def forward(self,x):
        query = x @ self.W_query
        key = x @ self.W_key
        value = x @ self.W_value

        attention_score = query @ key.T
        attention_weights = torch.softmax(attention_score/key.shape[-1]**0.5,dim=-1)
        context_vector = attention_weights @ value
        return context_vector

In [43]:
torch.manual_seed(123)
d_in = inputs.shape[1]
d_out = 2
sa = Self_Attention_V1(d_in,d_out)
sa(inputs)

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)

In [44]:
class Self_Attention_V2(torch.nn.Module):
    def __init__(self,d_in,d_out,qkv_bias=False):
        super().__init__()
        self.W_query = torch.nn.Linear(d_in,d_out,bias=qkv_bias)  # nn.Linear has better weights intilization , it also acts like layer in neutral network  
        self.W_key  = torch.nn.Linear(d_in,d_out,bias=qkv_bias)   
        self.W_value = torch.nn.Linear(d_in,d_out,bias=qkv_bias)

    def forward(self,x):
        query = self.W_query(x)
        key =   self.W_key(x)
        value = self.W_value(x)

        attention_score = query @ key.T
        att_dim = attention_score.shape[0]
        mask = torch.triu(torch.ones(att_dim,att_dim),diagonal = 1)
        masked_attention = attention_score.masked_fill(mask.bool(),-torch.inf)
        attention_weights = torch.softmax(masked_attention/key.shape[-1]**0.5,dim=-1)
        context_vector = attention_weights @ value
        return context_vector


In [45]:
torch.manual_seed(123)
d_in = inputs.shape[1]
d_out = 2
sa2 = Self_Attention_V2(d_in,d_out)
sa2(inputs)

tensor([[-0.4519,  0.2216],
        [-0.5874,  0.0058],
        [-0.6300, -0.0632],
        [-0.5675, -0.0843],
        [-0.5526, -0.0981],
        [-0.5299, -0.1081]], grad_fn=<MmBackward0>)

In [46]:
# step 1 taking vector embedded  inputs or 1st batch and do a dot product with wq,wk,wv
# Step 2 we get query ,key , values .take a dot product between query and transpose of key we get is attention score
# Step 3 From attention score do the masking since the first word  is only dependent on first , second wor is only dependent on 1st and 2nd  , 3rd is only dependent on 1,2,3 3rd word
# Step 4 devide masked attention score with root of number of columns of masked_attention score this is to reduce the variance to 1 
# step 5 add drop outs so that every vector learn 
# Step 6 softmax the masked_attention score matrix so that its normalized 
# Step 7 take a dot product with value matrix and we get context vector
# All this is done for all batches

In [47]:
class CausalAttention(torch.nn.Module):

    def __init__(self, d_in, d_out, context_length,
                 dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = torch.nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = torch.nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = torch.nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = torch.nn.Dropout(dropout) 
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1)) # New

    def forward(self, x):
        b, num_tokens, d_in = x.shape 

        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2) 

        attn_scores.masked_fill_(self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)  

        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)

        attn_weights = self.dropout(attn_weights) 

        context_vec = attn_weights @ values

        return context_vec

In [48]:
batch = torch.stack((inputs, inputs), dim=0)
print(batch.shape) 

torch.Size([2, 6, 3])


In [49]:
torch.manual_seed(123)

context_length = batch.shape[1]

ca = CausalAttention(d_in, d_out, context_length, 0.0)

context_vecs = ca(batch)

context_vecs.shape

torch.Size([2, 6, 2])

In [50]:
# Multihead attention with weight splits 
# Multihead means we do causal attention multiple times and the context vector we  get from each is concatinated all together for that particular token 
# weight splits mean instead of taking dot product between wq,wk,wv for all the casual attention seperately we do it together and split the attention score based on the number of causl attention


In [51]:
class Multi_Head_Attention(torch.nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout_rate, num_heads, qkv_bias=False):
        super().__init__()
        assert (d_out % num_heads == 0),"d_out must be divisible by num_heads"

        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads 

        self.W_query = torch.nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = torch.nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = torch.nn.Linear(d_in, d_out, bias=qkv_bias) 

        self.Dropout = torch.nn.Dropout(dropout_rate)

        self.register_buffer("mask",torch.triu(torch.ones(context_length, context_length),diagonal=1))

    def forward(self,x):
        batch , number_of_tokens , d_in = x.shape
        
        self.query = self.W_query(x)
        self.key = self.W_key(x)
        self.value = self.W_value(x)

        query = self.query.view(batch,number_of_tokens,self.num_heads,self.head_dim) #Adjusting size for all heads 
        key = self.key.view(batch,number_of_tokens,self.num_heads,self.head_dim)
        value = self.value.view(batch,number_of_tokens,self.num_heads,self.head_dim)
        
        key = key.transpose(1, 2)
        query = query.transpose(1, 2)
        value = value.transpose(1, 2)

        attention_score = query @ key.transpose(2,3)
        
         # Converting to true or false matrix and shaping to number of tokens
        mask_bool = self.mask.bool()[:number_of_tokens, :number_of_tokens]

        attention_score.masked_fill_(mask_bool,-torch.inf)

        attention_weights = torch.softmax(attention_score/self.head_dim**0.5,dim=-1)

        attention_weights = self.Dropout(attention_weights)

        context_vector = (attention_weights @ value).transpose(1,2)
       
        context_vector = context_vector.contiguous().view(batch,number_of_tokens,self.d_out)
        return context_vector

In [52]:

torch.manual_seed(123)
inputs = torch.tensor(
    [[0.43, 0.15, 0.89, 0.55, 0.87, 0.66],  # Row 1
     [0.57, 0.85, 0.64, 0.22, 0.58, 0.33],  # Row 2
     [0.77, 0.25, 0.10, 0.05, 0.80, 0.55]]  # Row 3
)
batch = torch.stack((inputs, inputs), dim=0)
print(batch.shape) 

torch.Size([2, 3, 6])


In [53]:

batch_size, context_length, d_in = batch.shape
d_out = 6
mha = Multi_Head_Attention(d_in, d_out, context_length, 0.0, num_heads=2)
context_vecs = mha(batch)
print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tensor([[[-0.1354,  0.2538,  0.1353,  0.0993,  0.5164,  0.1103],
         [-0.2447,  0.3172, -0.0060,  0.1318,  0.6144,  0.0032],
         [-0.2898,  0.2501,  0.0070,  0.0092,  0.5663,  0.0665]],

        [[-0.1354,  0.2538,  0.1353,  0.0993,  0.5164,  0.1103],
         [-0.2447,  0.3172, -0.0060,  0.1318,  0.6144,  0.0032],
         [-0.2898,  0.2501,  0.0070,  0.0092,  0.5663,  0.0665]]],
       grad_fn=<ViewBackward0>)
context_vecs.shape: torch.Size([2, 3, 6])


In [54]:
class Layer_normalization(torch.nn.Module):
    def __init__(self,emb_dim):
        super().__init__()
        self.epsilon = 1e-5
        self.scale = torch.nn.Parameter(torch.ones(emb_dim))
        self.shift = torch.nn.Parameter(torch.zeros(emb_dim))

    def forward(self,x):
        mean = x.mean(dim=-1,keepdim=True)
        variance = x.var(dim=-1,keepdim=True,unbiased=False)
        norm_x = (x-mean)/torch.sqrt(variance+self.epsilon)
        return self.scale*norm_x+self.shift

In [55]:
class Gelu(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self,x): # GELU activation function:
        # f(x) = 0.5 * x * (1 + tanh(sqrt(2/pi) * (x + 0.044715 * x^3)))
        return 0.5*x*(1+torch.tanh(torch.sqrt(torch.tensor(2.0/torch.pi))*(x+0.044715*torch.pow(x,3))))

In [56]:
class Feed_forward(torch.nn.Module):
    def __init__(self,cfg):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(cfg["emb_dim"],4*cfg["emb_dim"]),
            Gelu(),
            torch.nn.Linear(4*cfg["emb_dim"],cfg["emb_dim"])
        )
    def forward(self,x):
        return self.layers(x)

In [57]:
 # CHAT-GPT 2 parameters
GPT_CONFIG_124M = {
    "vocab_size": 50257,    # Vocabulary size
    "context_length": 1024, # Context length
    "emb_dim": 768,         # Embedding dimension
    "n_heads": 12,          # Number of attention heads
    "n_layers": 12,         # Number of layers
    "drop_rate": 0.1,       # Dropout rate
    "qkv_bias": False       # Query-Key-Value bias
}

In [58]:
class TransformerBlock(torch.nn.Module):
    def __init__(self,cfg):
        super().__init__()

        self.att = Multi_Head_Attention( d_in=cfg["emb_dim"],
                                        d_out=cfg["emb_dim"],
                                        context_length=cfg["context_length"],
                                        dropout_rate=cfg["drop_rate"], 
                                        num_heads=cfg["n_heads"],
                                        qkv_bias=cfg["qkv_bias"])
        
        self.layer_norm1 = Layer_normalization(emb_dim=cfg["emb_dim"])

        self.layer_norm2 = Layer_normalization(emb_dim=cfg["emb_dim"])

        self.feed_forward = Feed_forward(cfg=cfg)

        self.dropout = torch.nn.Dropout(cfg["drop_rate"])

    def forward(self,x):
        shortcut =x
        x = self.layer_norm1(x)
        x = self.att(x)
        x = self.dropout(x)
        x = x+shortcut
        shortcut = x
        x = self.layer_norm2(x)
        x = self.feed_forward(x)
        x = self.dropout(x)
        x = x + shortcut
        return x
    

In [59]:
torch.manual_seed(123)
x = torch.rand(2, 4, 768) 

block = TransformerBlock(GPT_CONFIG_124M)
output = block(x)

print("Input shape:", x.shape)
print("Output shape:", output.shape)

Input shape: torch.Size([2, 4, 768])
Output shape: torch.Size([2, 4, 768])
